language: java
dist: trusty
jdk: oraclejdk8
install: true
addons:
  apt:
    packages:
      - openjdk-8-jdk
  sonarcloud:
    organization: "spablohe-github"
    token:
      secure: fbfcccc4f3d62f620f5103c9cc8935cd81258133
script:
  - ./mvnw clean install
  - sonar-scanner
deploy:
  provider: heroku
  api_key: 
    secure: 36ca5c53-cbd9-4238-852d-3dbb245ed7e3
  app: lucius-tool
  on:
    repo: spablohe/lucius-tool
    