language: java
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: "spablohe-github"
    token:
      secure: f887959694bbbe07ab25fd5ecd4900ad0875aa8d
script:
  - ./mvnw sonar:sonar -Dsonar.projectKey=spablohe_lucius-tool -Dsonar.organization=spablohe-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=f887959694bbbe07ab25fd5ecd4900ad0875aa8d
  - ./mvnw clean install
deploy:
  provider: heroku
  api_key: 
    secure: 36ca5c53-cbd9-4238-852d-3dbb245ed7e3
  app: lucius-tool
  on:
    repo: spablohe/lucius-tool
    