language: java
dist: trusty
jdk: oraclejdk8
install: true
addons:
  apt:
    packages:
      - openjdk-8-jdk
  sonarcloud:
    organization: "spablohe-github"
    token: fbfcccc4f3d62f620f5103c9cc8935cd81258133
script:
  - ./mvnw clean install
  - sonar-scanner
deploy:
  provider: heroku
  api_key: 
    secure: 9cb6457b-28ef-43e5-abda-b3c80cc9b6da
  app: lucius-tool
  on:
    repo: spablohe/lucius-tool
    